name: Deploy to github pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup nodejs
        uses: actions/setup-node@v2
#         with:
#           node-version: '14'

      - name: Install node packages
        run: npm ci

      - name: Build
        run: npm run ng -- build --prod --base-href=https://${{ github.repository_owner }}.github.io/jukebox/ --output-path=${{ runner.temp }}/${{ github.sha }}

      - name: Preprocessing
        run: |
          git fetch origin
          git checkout gh-pages
          rm -rf ./node_modules
          mv -v ${{ runner.temp }}/${{ github.sha }}/** ./

      - name: Check changes
        id: changes
        run: |
          git add -N .
          echo "::set-output name=ischange::$(git diff --name-only | wc -l)"

      - name: debug
        run: |
          echo ${{ steps.changes.outputs.ischange }}

      - name: Push github pages
        run: |
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Deploy to github pages - ${{ github.sha }}"
          git push origin
        if: steps.changes.outputs.ischange > 0







#          git add -N .
#          if ! git diff --exit-code --quiet; then
#            git config user.name "${{ github.actor }}"
#            git add .
#            git commit -m "Deploy to github pages - ${{ github.sha }}"
#            git push origin
#          fi













